Pustok/Pustok/Controllers/BookDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pustok.DAL;
using Pustok.Models;
using Pustok.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pustok.Controllers
{
    public class BookDetailController : Controller
    {
        private readonly AppDbContext _context;

        public BookDetailController(AppDbContext context)
        {
            this._context = context;
        }

        public IActionResult Detail(int Id) 
        {
            Books book = _context.Book
                .Include(x=>x.BookImages)
                .Include(x=>x.Genre)
                .Include(x=>x.Author)
                .Include(x=>x.BookTags).ThenInclude(x=>x.Tags)
                .FirstOrDefault(x => x.Id == Id);
            BookDetailViewModel bookVW = new BookDetailViewModel
            {
                Book = book,
                RelatedBooks = _context.Book.Include(x=>x.Author)
                .Include(x=>x.Genre)
                .Include(x=>x.BookImages)
                .Where(x => x.GenreId == book.GenreId).Take(6).ToList(),
            
            };
            return View(bookVW);

        }

        public IActionResult GetBookModal(int id)
        {
            Books book = _context.Book.Include(x => x.Author).Include(x => x.Genre).Include(x => x.BookImages).FirstOrDefault(x=>x.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return PartialView("_BookModalPartial",book);
        }
    }
}

Pustok/Pustok/Views/Shared/_BookModalPartial.cshtml
@model Books

<button type="button" class="close modal-close-btn ml-auto" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
<div class="product-details-modal">
    <div class="row">
        <div class="col-lg-5">
            <img class="poster-img" src="~/upload/book/@Model.BookImages.FirstOrDefault(x=>x.PosterStatus == true)?.Name" alt="">
        </div>
        <div class="col-lg-7 mt--30 mt-lg--30">
            <div class="product-details-info pl-lg--30 ">
                <p class="tag-block">Tags: <a href="#">Movado</a>, <a href="#">Omega</a></p>
                <h3 class="product-title">@Model.Name</h3>
                <ul class="list-unstyled">
                    <li>Author: <span class="list-value"> @Model.Author</span></li>
                    <li>Genre: <a href="#" class="list-value font-weight-bold">@Model.Genre</a></li>
                    <li>Name: <span class="list-value"> @Model.Name</span></li>
                    <li>Page Size: <span class="list-value"> @Model.PageSize</span></li>

                </ul>
                <div class="price-block">
                    @if (Model.DiscountPercent > 0)
                    {
                        double discountedPrice = Model.SalePrice * (100 - Model.DiscountPercent) / 100;
                        <span class="price-new">$@discountedPrice</span>
                        <del class="price-old">$@Model.SalePrice</del>
                    }
                    else
                    {
                        <span class="price-new">$@Model.SalePrice</span>
                    }
                </div>
                <div class="rating-widget">
                    <div class="rating-block">
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star star_on"></span>
                        <span class="fas fa-star "></span>
                    </div>
                    <div class="review-widget">
                        <a href="#">(1 Reviews)</a> <span>|</span>
                        <a href="#">Write a review</a>
                    </div>
                </div>
                <article class="product-details-article">
                    <h4 class="sr-only">Product Summery</h4>
                    <p>
                        Long printed dress with thin adjustable straps. V-neckline and wiring under
                        the Dust with ruffles
                        at the bottom
                        of the
                        dress.
                    </p>
                </article>
                <div class="add-to-cart-row">
                    <div class="count-input-block">
                        <span class="widget-label">Qty</span>
                        <input type="number" class="form-control text-center" value="1">
                    </div>
                    <div class="add-cart-btn">
                        <a href="#" class="btn btn-outlined--primary">
                            <span class="plus-icon">+</span>Add to Cart
                        </a>
                    </div>
                </div>
                <div class="compare-wishlist-row">
                    <a href="#" class="add-link"><i class="fas fa-heart"></i>Add to Wish List</a>
                    <a href="#" class="add-link"><i class="fas fa-random"></i>Add to Compare</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="widget-social-share">
        <span class="widget-label">Share:</span>
        <div class="modal-social-share">
            <a href="#" class="single-icon"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-twitter"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-youtube"></i></a>
            <a href="#" class="single-icon"><i class="fab fa-google-plus-g"></i></a>
        </div>
    </div>
</div>

Pustok/Pustok/Views/Shared/_BookTabSliderPartial.cshtml
@model List<Books>
<div class="product-slider multiple-row  slider-border-multiple-row  sb-slick-slider"
     data-slick-setting='{
                            "autoplay": true,
                            "autoplaySpeed": 8000,
                            "slidesToShow": 5,
                            "rows":1,
                            "dots":true
                        }' data-slick-responsive='[
                            {"breakpoint":1200, "settings": {"slidesToShow": 3} },
                            {"breakpoint":768, "settings": {"slidesToShow": 2} },
                            {"breakpoint":480, "settings": {"slidesToShow": 1} },
                            {"breakpoint":320, "settings": {"slidesToShow": 1} }
                        ]'>

    @foreach (var item in Model)
    {
        <div class="single-slide">
            <div class="product-card">
                <div class="product-header">
                    <a href="#" class="author">
                        @item.Author.FullName
                    </a>
                    <h3>
                        <a asp-controller="BookDetail" asp-action="Detail" asp-route-Id="@item.Id">
                            @item.Name
                        </a>
                    </h3>
                </div>
                <div class="product-card--body">
                    <div class="card-image">
                        <img src="~/upload/book/@item.BookImages.FirstOrDefault(x=>x.PosterStatus == true)?.Name" alt="">
                        <div class="hover-contents">
                            <a href="product-details.html" class="hover-image">
                                <img src="~/upload/book/@item.BookImages.FirstOrDefault(x=>x.PosterStatus == false)?.Name" alt="">
                            </a>
                            <div class="hover-btns">
                                <a href="cart.html" class="single-btn">
                                    <i class="fas fa-shopping-basket"></i>
                                </a>
                                <a href="wishlist.html" class="single-btn">
                                    <i class="fas fa-heart"></i>
                                </a>
                                <a  class="single-btn">
                                    <i class="fas fa-random"></i>
                                </a>

                                <a asp-controller="BookDetail" asp-action="GetBookModal" asp-route-id="@item.Id"
                                   class="single-btn get-modal">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="price-block">
                        @if (item.DiscountPercent > 0)
                        {
                            double discountedPrice = item.SalePrice * (100 - item.DiscountPercent) / 100;
                            <span class="price">£@discountedPrice</span>
                            <del class="price-old">@item.SalePrice</del>
                            <span class="price-discount">@item.DiscountPercent%</span>
                        }
                        else
                        {
                            <span class="price">£@item.SalePrice</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }

</div>

Pustok/Pustok/Views/Shared/_MemberLoginFormPartial.cshtml
@model MemberLoginViewModel
<form asp-action="Login">
    <div class="login-form">
        <h4 class="login-title">Returning Customer</h4>
        <p><span class="font-weight-bold">I am a returning customer</span></p>
        <div class="row">
            <div class="col-md-12 col-12 mb--15">
                <label asp-for="LoginUserName">Enter your email address here...</label>
                <input asp-for="LoginUserName" class="mb-0 form-control" id="email1" placeholder="Enter you user name here...">
                <span asp-validation-for="LoginUserName"></span>
            </div>
            <div class="col-12 mb--20">
                <label asp-for="LoginPassword">Password</label>
                <input asp-for="LoginPassword" class="mb-0 form-control" id="login-password" placeholder="Enter your password">
                <span asp-validation-for="LoginPassword"></span>
            </div>
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-outlined">Login</button>
            </div>
        </div>
    </div>
</form>

Pustok/Pustok/Views/Shared/_MemberRegisterFormPartial.cshtml
@model MemberRegisterViewModel
<form asp-action="register" method="post">
    <div class="login-form">
        <h4 class="login-title">New Customer</h4>
        <p><span class="font-weight-bold">I am a new customer</span></p>
        <div class="row">
            <div class="col-md-12 col-12 mb--15">
                <label asp-for="FullName">Full Name</label>
                <input asp-for="FullName" class="mb-0 form-control" placeholder="Enter your full name">
                <span asp-validation-for="FullName"></span>

            </div>
            <div class="col-md-12 col-12 mb--15">
                <label asp-for="RegisterUserName">User Name</label>
                <input asp-for="RegisterUserName" class="mb-0 form-control" placeholder="Enter your user name">
                <span asp-validation-for="RegisterUserName"></span>

            </div>
            <div class="col-12 mb--20">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" class="mb-0 form-control" id="email" type="email" placeholder="Enter Your Email Address Here..">
                <span asp-validation-for="FullName"></span>
            </div>
            <div class="col-lg-6 mb--20">
                <label asp-for="RegisterPassword">Password</label>
                <input asp-for="RegisterPassword" class="mb-0 form-control" id="password" placeholder="Enter your password">
                <span asp-validation-for="RegisterPassword"></span>
            </div>
            <div class="col-lg-6 mb--20">
                <label asp-for="ConfirmPassword">Repeat Password</label>
                <input asp-for="ConfirmPassword" class="mb-0 form-control" type="password" id="repeat-password" placeholder="Repeat your password">
                <span asp-validation-for="ConfirmPassword"></span>
            </div>
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-outlined">Register</button>
            </div>
        </div>
    </div>
</form>